name: Locale Workflow

on: push

permissions:
  contents: write        # Grants permission to write to the repository
  pull-requests: write   # Grants permission to manage pull requests


jobs:
  create-branch-and-pr-on-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessary to ensure history is available for branch operations

      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Get the last commit message
        id: get-commit-message
        run: echo "::set-output name=message::$(git log -1 --pretty=format:%s)"

      - name: Create new branch and push if commit message matches
        id: create_branch
        if: steps.get-commit-message.outputs.message == 'Localyzer Git S3 Integration'
        run: |
          NEW_BRANCH="lingoport-translations-updates-$(date +%Y-%m-%d)"
          git checkout lingo-test
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH
          echo "::set-output name=branch_name::$NEW_BRANCH"
          echo "New branch created: $NEW_BRANCH"

      - name: Create Pull Request
        if: steps.create_branch.outputs.branch_name
        run: |
          gh pr create --title "Review new locale updates" \
                       --body "Please review the changes in this new branch: ${{ steps.create_branch.outputs.branch_name }}" \
                       --base main \
                       --head ${{ steps.create_branch.outputs.branch_name }}